spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ioj
    username: insert
    password: insert1234
    hikari:
      maxLifetime: 580000
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql

naver:
  naver_c: ${A}
  naver_s: ${S}

auth:
  google:
    base-url: https://accounts.google.com/o/oauth2/auth
    client-id: 582862839129-ati79d5ean376nbradcej6qjok6hkcfh.apps.googleusercontent.com
    redirect-url: http://localhost:3000/google/callback

jwt:
  refresh-time: 2592000000
  access-time: 3600000
  prefix: Bearer
  header: Authorization
  secret-key: insert1234!!

