spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: root
    password:
    hikari:
      maxLifetime: 580000
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        characterEncoding: UTF-8
        useUnicode: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql

naver:
  naver_c: ${A}
  naver_s: ${S}

auth:
  google:
    base-url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: 889367937280-n63ri216vealltnbifoko7p14gh14jn8.apps.googleusercontent.com
    redirect-url: http://localhost:3000/google/callback




jwt:
  refresh-time: 2592000000
  access-time: 999999999999999999
  prefix: Bearer
  header: Authorization
  secret-key: sdfsdfds
